# Generated by Django 4.2.23 on 2025-07-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_profile_image_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='zoom_level',
            field=models.IntegerField(default=1),
        ),
    ]
